### ISSUE TITLE
Menuitem "About Fraise"

### ISSUE THREAD

**Issue by ekuester** [abentele/Fraise#15]
First I could not believe it: Fraise, my absolutely favoured Text editor is working again under 10.12! Very good work, I have tried it myself, but the huge amount of errors when converting from Garbage Collection to ARC were beyond my capabilities.
So, I want to encourage you to immortalise your name in credits.rtf ...
Maybe I can be of help eventually with the syntax definitions for Swift?
PS: A dream of mine were converting Fraise Objective-C to Swift ...

**Comment by abentele** [comment]
Thanks! Yes, this is currently the only maintained branch for Fraise, and also working with macOS Sierra. My main goal is to maintain Fraise working on the current release of macOS.

Credits are already updated, not to immortalise my name, but to tell who maintains this branch.

If you want to contribute syntax definitions for Swift: create a fork of my branch, implement it and create a pull request. I will try to support you if you have any questions.

Converting Fraise code to Swift would be a very time consuming task, and I have no idea what effort it would be (to make it not only compile but also stable!). I also thought about that, but in my opinion currently it's more important (for the end user) to make Fraise more stable on macOS Sierra.

Because this issue is only about the menu item "About Fraise", I will close because it's already done.
If you want to discuss about the other things in more detail, please open more specific issues.
